flows:
    oauth:
        enabled: true
        providers:
            authentik:
                type: oauth2
                client_id: AOpFLLKhyCVpNHcbZXaObFzR03kisJKvrniTWvVI
                client_secret: APe5D7SWRHB3iYWksVVOY21UsIqAHWS0UYMjUGVUEpFSneFkWVQxqVfXmtxEZwdUuYVBniZ9IopevMqA7IGYiQEWivR9TnvE9yYn5ZGdoAPL94HoooBdX37KkGN5Mjxe
                base_url: http://authentik-server-1.dns.podman:9000/
                access_token_url: http://authentik-server-1.dns.podman:9000/application/o/token/
                authorize_url: http://authentik-server-1.dns.podman:9000/application/o/authorize/
                user_info_url: http://authentik-server-1.dns.podman:9000/application/o/userinfo/
                long_name: Authentik
                short_name: authentik
                scope: profile openid email
                username_attribute: preferred_username
